services:
  auth_db:
    image: postgres:16
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authuser -d authdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth_service:
    build: ./services/auth_service
    volumes:
      - ./services/auth_service:/app
    env_file:
      - ./services/auth_service/.env.example
    depends_on:
      auth_db:
        condition: service_healthy
    ports:
      - "8001:8000"

    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "  

  # profiles
  profile_db:
    image: postgres:16
    environment:
      POSTGRES_DB: profiledb
      POSTGRES_USER: profileuser
      POSTGRES_PASSWORD: profilepass
    volumes:
      - profile_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U profileuser -d profiledb" ]

      interval: 5s
      timeout: 5s
      retries: 5

  profile_service:
    build: ./services/profile_service
    volumes:
      - ./services/profile_service:/app
    env_file:
      - ./services/profile_service/.env.example
    depends_on:
      profile_db:
        condition: service_healthy
    ports:
      - "8002:8000"
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  # board
#  board_db:
#    image: postgres:16
#    environment:
#      POSTGRES_DB: boarddb
#      POSTGRES_USER: boarduser
#      POSTGRES_PASSWORD: boardpass
#    volumes:
#      - board_db_data:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U boarduser"]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#
#  board_service:
#    build: ./services/board_service
#    env_file:
#      - ./services/board_service/.env
#    depends_on:
#      board_db:
#        condition: service_healthy
#    ports:
#      - "8003:8000"
#    command: >
#      sh -c "
#      alembic upgrade head &&
#      uvicorn app.main:app --host 0.0.0.0 --port 8000
#      "

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
  auth_db_data:
  profile_db_data:
#  board_db_data:

