name: CI

on:
  push:
  pull_request:

jobs:
  pylint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pip install uv

      - name: Lint auth service
        run: |
          cd services/auth_service
          uv sync
          uv run pylint app --fail-under=1.0

      - name: Lint profile service
        run: |
          cd services/profile_service
          uv sync
          uv run pylint app --fail-under=1.0

  unit-tests:
    runs-on: ubuntu-latest
    needs: pylint-test
    strategy:
      matrix:
        service: [auth_service, board_service, profile_service]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: pip install uv

      - name: Run tests (${{ matrix.service }})
        run: |
          cd services/${{ matrix.service }}
          uv sync --group dev
          if [ "${{ matrix.service }}" = "board_service" ]; then
            uv run pytest --cov=app --cov-report=term-missing
          else
            uv run pytest
          fi


  docker-test:
    runs-on: ubuntu-latest
    needs:
      - unit-tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and start services
        run: docker compose up -d --build

      - name: Shutdown
        run: sleep 15

      - name: Show container status
        run: docker ps

      - name: Stop services
        if: always()
        run: docker compose down



